---
# Tasks for print_stats
- name: Print statistics
  ansible.builtin.debug:
    msg:
      - 'List of problem VMs:'
      - "{{ problematic_list | default([]) }}"
      - 'List of offline VMs:'
      - "{{ offline_list | default([]) }}"
      - 'List of non updated VMs:'
      - "{{ noupdate_list | default([]) }}"
      - 'List of Snapshots:'
      - "{{ snapshots_list | default([]) }}"
      - "faulties_number = {{ problematic_list | default([]) | length }}"
      - "offlines_number = {{ offline_list | default([]) | length }}"
      - "noupdate_number = {{ noupdate_list | default([]) | length }}"
      - "snaps_number = {{ snapshots_counter | default(0) }}"
      - "snaps_size = {{ ('%0.2f' | format(snapshots_size | default(0) | float / 1024 | pow(4))) | string + ' TiB' if \
        (snapshots_size | default(0) | int) | string | length > 12 else \
        ('%0.2f' | format(snapshots_size | default(0) | float / 1024 | pow(3))) | string + ' GiB' if \
        (snapshots_size | default(0) | int) | string | length > 9 else \
        ('%0.2f' | format(snapshots_size | default(0) | float / 1024 | pow(2))) | string + ' MiB' }}"
      - 'List of decommissioning candidate VMs:'
      - "{{ decomm_vm_list | default([]) }}"
      - "decomms_number = {{ decomm_vm_list | default([]) | length }}"
      - 'List of deleted VMs:'
      - "{{ deleted_vm_list | default([]) }}"
      - "deleted_number = {{ deleted_vm_list | default([]) | length }}"
  delegate_to: localhost
  run_once: true
  tags: ['always', 'print_stats']
