---
# tasks to remove DNS records for deleted VM
- ansible.builtin.include_tasks:
    file: task_delete_forward_record.yml
    apply:
      vars:
        mydesignation: "decommissioned VM {{ vm_name }}"
        myserver: "{{ name_server }}"
        mydomain: "{{ domain_name }}"
        myrecord: "{{ vm_name }}"
        myipaddress: "{{ vm_ip }}"
- ansible.builtin.include_tasks:
    file: task_delete_reverse_record.yml
    apply:
      vars:
        mydesignation: "decommissioned VM {{ vm_name }}"
        myserver: "{{ name_server }}"
        mydomain: "{{ domain_name }}"
        myrecord: "{{ vm_name }}"
        myipaddress: "{{ vm_ip }}"
