---
# tasks to remove DNS records for deleted VM
- name: Delete forward record
  ansible.builtin.include_tasks:
    file: task_delete_forward_record.yml
    apply:
      vars:
        mydesignation: "decommissioned VM {{ vm_name }}"
        myserver: "{{ name_server }}"
        mydomain: "{{ domain_name }}"
        myrecord: "{{ vm_name }}"
- name: Delete reverse record
  ansible.builtin.include_tasks:
    file: task_delete_reverse_record.yml
    apply:
      vars:
        mydesignation: "decommissioned VM {{ vm_name }}"
        myserver: "{{ name_server }}"
        mydomain: "{{ domain_name }}"
        myrecord: "{{ vm_name }}"
        myipaddress: "{{ vm_ip }}"
  when:
    - vm_ip | default('') != ''
