---
# Task file to delete forward DNS record
- name: Delete forward DNS record
  delegate_to: localhost
  block:
    - name: Remove {{ mydesignation + ' DNS record' }}
      ansible.builtin.shell: |
        {% if myserver is search('172.(23|30)') %}
        sshpass -p {{ svc_password }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T -l {{ svc_username }} {{ lookup('env', 'MYIP') }} <<EOF
        {% endif %}
        nsupdate {% if myserver is search('172.(23|30)') %}-g {% endif %}<<EOC
        server {{ myserver }}
        update delete {{ myrecord }}.{{ mydomain }} A
        send
        EOC
        {% if myserver is search('172.(23|30)') %}
        EOF
        {% endif %}
      register: reg_fdr
      changed_when: reg_fdr.rc == 0
      failed_when: reg_fdr.rc != 0 and reg_fdr.stderr is not search('tsig verify failure')
      until: reg_fdr is succeeded
      delay: 10
      no_log: true
  rescue:
    - name: Debug message
      ansible.builtin.debug:
        msg: "{{ reg_fdr | replace(svc_password, 'obfuscated') if svc_password != '' else reg_fdr }}"
  always:
    - name: Assert that removing the forward DNS record succeeded
      ansible.builtin.assert:
        that: reg_fdr is succeeded
