---
# Tasks to delete a VM in a given folder
- name: get info for {{ curr_vm }} in {{ curr_folder }}
  community.vmware.vmware_guest_info:
    hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
    username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
    password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
    datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
    folder: "{{ curr_folder }}"
    uuid: "{{ curr_uuid }}"
    validate_certs: no
  register: reg_guest_info
  no_log: yes
  ignore_errors: yes
- block:
  - name: Delete VM
    community.vmware.vmware_guest:
      hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
      username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
      password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
      datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
      folder: "{{ curr_folder }}"
      uuid: "{{ curr_uuid }}"
      state: absent
      force: yes
      validate_certs: no
  - name: update list of deleted VMs
    ansible.builtin.set_fact:
      deleted_vm_list: "{{ deleted_vm_list|default([]) + [curr_folder + ': ' + curr_vm] }}"
  when:
    - reg_guest_info.instance.customvalues|dict2items|selectattr('key','search','date-todecomm')|list != {}
    - (ansible_date_time.date|to_datetime('%Y-%m-%d') - reg_guest_info.instance.customvalues|dict2items|selectattr('key','search','date-todecomm')|map(attribute='value')|list|join|to_datetime('%Y-%m-%d')).days|int >= 0
- ansible.builtin.fail:
    msg: VMs in this VCenter do not have the required custom attributes for the VM decommissioning process
  when: reg_guest_info.instance.customvalues|dict2items|selectattr('key','search','date-todecomm')|list == {}