---
# Tasks to delete the VM folder path
- name: Initialize list of sub folders
  ansible.builtin.set_fact:
    sub_folder_list: "{{ [curr_folder] }}"
- name: Define list of sub folders
  ansible.builtin.set_fact:
    sub_folder_list: "{{ sub_folder_list + [sub_folder] }}"
  when: sub_folder != ''
  vars:
    sub_folder: "{{ curr_folder.split('/')[: -(loop_item | int)] | join('/') }}"
  loop: "{{ range(1, curr_folder.split('/') | list | length) }}"
  loop_control:
    loop_var: loop_item
- name: Initialize folder_empty
  ansible.builtin.set_fact:
    folder_empty: false
    exit_delete_loop: false
- name: Delete folder
  ansible.builtin.include_tasks:
    file: task_delete_folder.yml
    apply:
      vars:
        folder_name: "{{ subfolder_item }}"
  loop: "{{ sub_folder_list }}"
  loop_control:
    loop_var: subfolder_item
