---
# Task file to delete reverse DNS record
- name: Delete reverse DNS record
  delegate_to: localhost
  block:
    - name: Remove {{ mydesignation + ' reverse DNS record' }}
      ansible.builtin.shell: |
        {% if myserver is search('172.(23|30)') %}
        sshpass -p {{ svc_password }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T -l {{ svc_username }} {{ lookup('env', 'MYIP') }} <<EOF
        {% endif %}
        nsupdate {% if myserver is search('172.(23|30)') %}-g {% endif %}<<EOC
        server {{ myserver }}
        zone {{ myipaddress.split('.')[:-1] | reverse | join('.') + '.in-addr.arpa' }}
        update delete {{ myipaddress.split('.') | reverse | join('.') + '.in-addr.arpa' }} PTR
        send
        EOC
        {% if myserver is search('172.(23|30)') %}
        EOF
        {% endif %}
      register: reg_rdr
      changed_when: reg_rdr.rc == 0
      failed_when: reg_rdr.rc != 0 and reg_rdr.stderr is not search('tsig verify failure')
      until: reg_rdr is succeeded
      delay: 10
      no_log: true
  rescue:
    - name: Debug message
      ansible.builtin.debug:
        msg: "{{ reg_rdr | replace(svc_password, 'obfuscated') if svc_password != '' else reg_rdr }}"
  always:
    - name: Assert that removing the reverse DNS record succeeded
      ansible.builtin.assert:
        that: reg_rdr is succeeded
      when: myserver is search('172.(23|30)')
