---
# Tasks for VM snapshots
- name: Main remove_snapshots block
  delegate_to: localhost
  run_once: true
  tags: ['remove_snapshots']
  block:
    - name: Get date and time
      ansible.builtin.include_tasks: task_get_date_time.yml
      when:
        - ansible_date_time.date is not defined
        - ansible_date_time.date | default('') == ''
    - name: Define get_vm_list_rs
      ansible.builtin.set_fact:
        get_vm_list_rs: true
      when: reg_vm_list is not defined
    - name: Get the list of VMs
      when: get_vm_list_rs | default(true)
      block:
        - name: Get list of VMs
          ansible.builtin.include_tasks: task_get_list_vms.yml
      rescue:
        - name: Debug message
          ansible.builtin.debug:
            msg: "{{ reg_vm_list }}"
      always:
        - name: Assert that we got the list of VMs successfully
          ansible.builtin.assert:
            that: reg_vm_list is succeeded
    - name: Define build_list_rs
      ansible.builtin.set_fact:
        build_list_rs: true
      when: vm_list is not defined
    - name: Define list of VMs and on-decomm-list VMs
      when: build_list_rs | default(false)
      no_log: true
      block:
        - name: Define list of VMs
          ansible.builtin.set_fact:
            vm_list: "{{ vm_list | default([]) + [{'vm_folder': vm_item.folder, 'vm_name': vm_item.guest_name, 'vm_uuid': vm_item.uuid}] }}"
          loop: "{{ reg_vm_list.virtual_machines | rejectattr('guest_name', 'search', 'on-decomm-list|stCtlVM-') | \
            rejectattr('folder', 'search', 'Templates|vcenter|vCenter') | list }}"
          loop_control:
            loop_var: vm_item
            label: "{{ vm_item.guest_name }}"
        - name: Define list of on-decomm-list VMs
          ansible.builtin.set_fact:
            dvm_list: "{{ dvm_list | default([]) + [{'vm_folder': vm_item.folder, 'vm_name': vm_item.guest_name, 'vm_uuid': vm_item.uuid}] }}"
          loop: "{{ reg_vm_list.virtual_machines | selectattr('guest_name', 'search', 'on-decomm-list') | \
            rejectattr('folder', 'search', 'Templates|vcenter|vCenter') | list }}"
          loop_control:
            loop_var: vm_item
            label: "{{ vm_item.guest_name }}"
    - name: Populate the created date attribute
      ansible.builtin.include_tasks:
        file: task_populate_created_date.yml
        apply:
          vars:
            curr_folder: "{{ vm_item.vm_folder }}"
            curr_vm: "{{ vm_item.vm_name }}"
            curr_uuid: "{{ vm_item.vm_uuid }}"
      loop: "{{ dvm_list | default([]) | sort(attribute='vm_folder') }}"
      loop_control:
        loop_var: vm_item
    - name: Initialize list of offline VMs
      ansible.builtin.set_fact:
        offline_vm_list: []
        offline_list: []
    - name: Delete snapshots
      ansible.builtin.include_tasks:
        file: task_delete_snapshots.yml
        apply:
          vars:
            curr_folder: "{{ vm_item.vm_folder }}"
            curr_vm: "{{ vm_item.vm_name }}"
            curr_uuid: "{{ vm_item.vm_uuid }}"
      loop: "{{ vm_list | default([]) | sort(attribute='vm_folder') }}"
      loop_control:
        loop_var: vm_item
