---
# Tasks to get snapshots in a given folder
- block:
  - name: get the list of VMs in {{ curr_folder }}
    community.vmware.vmware_vm_info:
      hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
      username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
      password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
      folder: "{{ curr_folder }}"
      vm_type: vm
      validate_certs: no
    register: reg_vm_list
    no_log: yes
  - include_tasks:
      file: task_delete_snapshots.yml
      apply:
        vars:
          curr_vm: "{{ vm_item }}"
    when:
      - vm_item is not search('on-decomm-list')
    loop: "{{ vm_names }}"
    loop_control:
      loop_var: vm_item
    vars:
      vm_names: "{{ reg_vm_list.virtual_machines|map(attribute='guest_name')|list }}"
  tags: ['remove_snapshots']
