---
# Tasks for decomm_vm
- name: Main decomm_vm block
  delegate_to: localhost
  run_once: true
  tags: ['decomm_vm']
  block:
    - name: Get date and time
      ansible.builtin.include_role:
        name: remove_snapshots
        tasks_from: task_get_date_time.yml
      when:
        - ansible_date_time.date is not defined
        - ansible_date_time.date|default('') == ''
    - name: Process poweredon VM
      ansible.builtin.include_tasks: task_process_poweredon_vm.yml
    - name: Process powered off VM
      ansible.builtin.include_tasks: task_process_poweredoff_vm.yml
