---
# Tasks for decomm_vm
- name: define get_vm_list_dv_on
  ansible.builtin.set_fact:
    get_vm_list_dv_on: true
  when: reg_vm_list is not defined
- block:
  - ansible.builtin.include_role:
      name: remove_snapshots
      tasks_from: task_get_list_vms.yml
  rescue:
  - ansible.builtin.debug:
      msg: "{{ reg_vm_list }}"
  always:
  - ansible.builtin.assert:
      that: reg_vm_list is succeeded
  when:
    - get_vm_list_dv_on|default(false)
- name: define build_list_dv_on
  ansible.builtin.set_fact:
    build_list_dv_on: true
  when: vm_list is not defined
- name: define list of VMs
  ansible.builtin.set_fact:
    vm_list: "{{ vm_list|default([]) + [{ 'vm_folder': vm_item.folder, 'vm_name': vm_item.guest_name, 'vm_uuid': vm_item.uuid}] }}"
  loop: "{{ reg_vm_list.virtual_machines|rejectattr('guest_name','search','on-decomm-list|stCtlVM-')|rejectattr('folder','search','Templates|vcenter|vCenter')|list }}"
  loop_control:
    loop_var: vm_item
    label: "{{ vm_item.guest_name }}"
  no_log: yes
  when:
    - build_list_dv_on|default(false)
- name: define build_decomm_list_dv_on
  ansible.builtin.set_fact:
    build_decomm_list_dv_on: true
  when: vm_on_decomm_list is not defined
- name: define list of VMs to be decommissioned
  ansible.builtin.set_fact:
    vm_on_decomm_list: "{{ vm_on_decomm_list|default([]) + [{ 'vm_folder': vm_item.folder, 'vm_name': vm_item.guest_name, 'vm_uuid': vm_item.uuid}] }}"
  loop: "{{ reg_vm_list.virtual_machines|selectattr('folder','search','acme1')|selectattr('guest_name','search','on-decomm-list')|list }}"
  loop_control:
    loop_var: vm_item
    label: "{{ vm_item.guest_name }}"
  no_log: yes
  when:
    - build_decomm_list_dv_on|default(false)
- include_tasks:
    file: task_decommission_poweredon_vm.yml
    apply:
      vars:
        curr_folder: "{{ vm_item.vm_folder }}"
        curr_vm: "{{ vm_item.vm_name }}"
        curr_uuid: "{{ vm_item.vm_uuid }}"
  loop: "{{ vm_list|sort(attribute='vm_folder') }}"
  loop_control:
    loop_var: vm_item
- include_tasks:
    file: task_decommission_poweredon_vm.yml
    apply:
      vars:
        curr_folder: "{{ vm_item.vm_folder }}"
        curr_vm: "{{ vm_item.vm_name }}"
        curr_uuid: "{{ vm_item.vm_uuid }}"
  loop: "{{ vm_on_decomm_list|default([])|sort(attribute='vm_folder') }}"
  loop_control:
    loop_var: vm_item
