---
# Tasks to power-off the VM
- name: Power off VM
  block:
    - name: Power-off {{ vm_name }}
      community.vmware.vmware_guest:
        hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
        username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
        password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
        datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
        folder: "{{ folder_name }}"
        uuid: "{{ vm_uuid }}"
        state: poweredoff
        validate_certs: false
      register: reg_poweroff
      no_log: true
  rescue:
    - name: Debug message
      ansible.builtin.debug:
        msg: "{{ reg_poweroff }}"
  always:
    - name: Assert that powering off the VM succeeded
      ansible.builtin.assert:
        that: reg_poweroff is succeeded
